#!/bin/bash
# Quick start script for Roboboogie Avatar

echo "=== Roboboogie Avatar Quick Start ==="
echo ""
echo "Since Python packages can be tricky on macOS, here's the simplest option:"
echo ""
echo "1. Open the auto-animated version in your browser:"
echo "   open /Users/Josh/clawd/avatar/auto_avatar.html"
echo ""
echo "2. If you want it to always be visible, you can:"
echo "   - Open it in a separate browser window"
echo "   - Position it where you want"
echo "   - It automatically cycles through states"
echo "   - You can click and drag to move it"
echo ""
echo "Features of this version:"
echo "• Auto-cycles through all states (thinking, working, excited, etc.)"
echo "• Draggable (click and drag anywhere except buttons)"
echo "• Manual controls if you want to set a specific state"
echo "• No Python installation needed!"
echo ""
echo "To make it work with Clawdbot, we'll need to connect it to the"
echo "system later, but this is a great starting point."